image: golang:1.16

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml

stages:
  - test

unit_tests:
  stage: test
  script:
    - go test -race -cover ./...
